services:
  shiny-app:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./app.R:/srv/shiny-server/app.R
      - ./deploy.R:/home/shiny/deploy.R
    env_file:
      - .env
    restart: unless-stopped
